export const detailedHealthFixture = {
  ready: true, codexReady: true, provider: 'openai', model: 'gpt-6-astra', connectorVersion: 33,
  photoInput: true, promptMaxLength: 5000, astraBudgetRevision: 'astra-usd175-v1', astraBudgetMaxUsd: 1.75,
  astraBudgetPreflight: 'input-tokens', astraBudgetExpiry: 1793145600,
  astraOutputPolicy: 'astra-low-reconciled-v2', astraReasoningEffort: 'low', astraMaxOutputTokens: 16000,
  astraUsageSettlement: 'authenticated-completed-only',
}
/** Deterministic triangle with material; not generated by AI and not a character. */
export function detailedGLBFixture() {
  const doc = { asset: { version: '2.0' }, scene: 0, scenes: [{ nodes: [0] }], nodes: [{ mesh: 0 }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 }, material: 0 }] }], materials: [{ pbrMetallicRoughness: { baseColorFactor: [1,1,1,1] } }],
    buffers: [{ byteLength: 36 }], bufferViews: [{ buffer: 0, byteLength: 36 }],
    accessors: [{ bufferView: 0, componentType: 5126, count: 3, type: 'VEC3', min: [0,0,0], max: [1,1,0] }] }
  const raw = new TextEncoder().encode(JSON.stringify(doc)), padded = Math.ceil(raw.length/4)*4
  const bytes = new Uint8Array(28+padded+36), view = new DataView(bytes.buffer)
  view.setUint32(0,0x46546c67,true); view.setUint32(4,2,true); view.setUint32(8,bytes.length,true)
  view.setUint32(12,padded,true); view.setUint32(16,0x4e4f534a,true); bytes.fill(32,20,20+padded); bytes.set(raw,20)
  view.setUint32(20+padded,36,true); view.setUint32(24+padded,0x004e4942,true)
  ;[0,0,0,1,0,0,0,1,0].forEach((n,i)=>view.setFloat32(28+padded+i*4,n,true))
  return bytes
}
