import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { newGameWorld,validateGameWorld,addWorldObject,groundHeight,applyWorldProposal,proposeWorldCommand,GAME_TUTORIAL,WORLD_LIMITS,mergeWorldBlueprint } from '../src/lib/gameWorld.ts'
import { worldTools,registerWorldTools } from '../src/lib/gameWorldWebMcp.ts'
import { AccountEntitlements,type EntitlementStorage } from '../server/entitlements.ts'
import { gameWorldApi } from '../server/game-worlds.ts'
import { quoteGeneration } from '../src/lib/generationQuote.ts'
import { planEconomics,providerReserveCents } from '../server/generationEconomics.ts'
const OWNER='b8867f90-8703-4d20-b97e-4b6b4c24d142',OTHER='84d69075-9be3-4b70-b32c-b87bb714cae9'
function fixture(){const data=new Map<string,unknown>();let pending:Promise<unknown>=Promise.resolve();const storage:EntitlementStorage={async get<T>(key:string){return structuredClone(data.get(key)) as T|undefined},async put(key,value){data.set(key,structuredClone(value))},transaction<T>(fn:(s:EntitlementStorage)=>Promise<T>){const next=pending.then(()=>fn(storage));pending=next.catch(()=>{});return next}};let now=Date.parse('2026-09-29T04:00:00Z');let object=new AccountEntitlements({storage},{},()=>now);return{storage,data,get object(){return object},recreate(){object=new AccountEntitlements({storage},{},()=>now)},advance(){now+=32*86400000},now:()=>now,async call(path:string,body?:unknown){const r=await object.fetch(new Request('https://entitlements.internal'+path,{method:body===undefined?'GET':'POST',...(body===undefined?{}:{body:JSON.stringify(body)})}));return{status:r.status,value:await r.json() as any}}}}
test('a new personal game starts with only meadow, river and a separate character brief',()=>{const w=newGameWorld('My river',{name:'Maja',hair:'Blue',lettering:'EARTH'});assert.equal(w.objects.length,0);assert.equal(w.terrain.length,0);assert.equal(w.playerModelId,null);assert.equal(w.controls.length,0);assert.equal(w.character.hair,'Blue');assert.equal(w.revision,0);assert.equal(GAME_TUTORIAL.length,5);assert.ok(groundHeight(0,0)<0);assert.ok(groundHeight(-12,0)>0)})
test('portable world schema rejects owner injection, scripts, remote model URLs and oversized geometry plans',()=>{const w=newGameWorld('Mine');for(const x of [{...w,ownerId:OTHER},{...w,script:'fetch(secret)'},{...w,terrain:[{x:0,z:0,radius:Infinity,strength:2}]},{...w,objects:[{id:crypto.randomUUID(),name:'Remote',kind:'local-model',assetId:'https://example.com/model.glb',x:0,y:0,z:0,scale:1,rotation:0,color:'#ffffff'}]}])assert.throws(()=>validateGameWorld(x));const bad=newGameWorld('Huge');for(let i=0;i<81;i++)bad.objects.push({id:crypto.randomUUID(),name:'Rock',kind:'rock',assetId:null,x:1,y:0,z:1,scale:1,rotation:0,color:'#ffffff'});assert.throws(()=>validateGameWorld(bad));assert.throws(()=>newGameWorld('x'.repeat(81)))})
test('terrain and button commands change real bounded data without deleting existing placements',()=>{const w=addWorldObject(newGameWorld('Mine'),'tree',{x:-10,z:5});const p={x:-14,z:2};const hill=applyWorldProposal(w,proposeWorldCommand('postaw górę')!,p);assert.ok(groundHeight(p.x,p.z,hill.terrain)>groundHeight(p.x,p.z,w.terrain));assert.equal(hill.objects[0].id,w.objects[0].id);const valley=applyWorldProposal(w,proposeWorldCommand('wykop dolinę')!,p);assert.ok(groundHeight(p.x,p.z,valley.terrain)<groundHeight(p.x,p.z,w.terrain));let jump=applyWorldProposal(w,proposeWorldCommand('dodaj przycisk skoku')!,p);jump=applyWorldProposal(jump,proposeWorldCommand('add jump button')!,p);assert.equal(jump.controls.length,1);assert.equal(jump.controls[0].action,'jump');assert.equal(applyWorldProposal(w,proposeWorldCommand('show stars')!,p).sky,'stars');assert.equal(proposeWorldCommand('execute JavaScript fetch private data'),null);assert.throws(()=>applyWorldProposal(w,{command:'script'} as any,p))})
test('AI blueprints append validated objects and cannot replace an owned world identifier or terrain',()=>{const w=newGameWorld('Original');const next=mergeWorldBlueprint(w,{version:1,title:'AI title',biome:'lunar',objects:[{id:'rock',name:'Rock',kind:'rock',x:5,z:4,scale:1,rotation:0,color:'#aaaaaa'}]});assert.equal(next.id,w.id);assert.equal(next.name,w.name);assert.equal(next.sky,'day');assert.equal(next.objects.length,1);assert.throws(()=>mergeWorldBlueprint(w,{version:1,title:'Bad',biome:'valley',objects:[]}))})
test('account world store protects creation, concurrent revisions and persistence without touching payment data',async()=>{const a=fixture(),b=fixture(),w=newGameWorld('Private');await a.storage.put('balance',835);const response=await a.call('/game-worlds',{world:w,expectedRevision:0});assert.equal(response.status,200);assert.equal(response.value.world.revision,1);assert.equal((await b.call('/game-worlds')).value.worlds.length,0);assert.equal((await b.call('/game-worlds',{world:response.value.world,expectedRevision:1})).status,409);const saved=response.value.world;const pair=await Promise.all([a.call('/game-worlds',{world:{...saved,name:'A'},expectedRevision:1}),a.call('/game-worlds',{world:{...saved,name:'B'},expectedRevision:1})]);assert.equal(pair.filter(r=>r.status===200).length,1);assert.equal(pair.filter(r=>r.status===409).length,1);a.recreate();assert.equal((await a.call('/game-worlds')).value.worlds.length,1);assert.equal((await a.call('/status')).value.credits,835);assert.equal(a.data.has('provider-budget-cents:v1'),false)})
test('world storage enforces the eight-project ceiling, unknown fields and oversized body',async()=>{const a=fixture();for(let i=0;i<WORLD_LIMITS.projects;i++)assert.equal((await a.call('/game-worlds',{world:newGameWorld('World '+i),expectedRevision:0})).status,200);assert.equal((await a.call('/game-worlds',{world:newGameWorld('Too many'),expectedRevision:0})).status,409);assert.equal((await a.call('/game-worlds',{world:newGameWorld('Injection'),expectedRevision:0,ownerId:OTHER})).status,400);assert.equal((await a.call('/game-worlds',{junk:'a'.repeat(100000)})).status,413)})
test('public world API rejects cross-origin, query-owner and unsupported requests before network',async()=>{let calls=0;const network=async()=>{calls++;throw new Error('must not run')};const req=(path:string,origin?:string,method='POST')=>new Request('https://worldifact.test'+path,{method,headers:{'Content-Type':'application/json',...(origin?{Origin:origin}:{})},...(method==='GET'?{}:{body:'{}'})});assert.equal((await gameWorldApi(req('/api/game-worlds','https://attacker.test'),{},network as any))!.status,403);assert.equal((await gameWorldApi(req('/api/game-worlds'),{},network as any))!.status,403);assert.equal((await gameWorldApi(req('/api/game-worlds?owner='+OTHER,undefined,'GET'),{},network as any))!.status,400);assert.equal((await gameWorldApi(req('/api/game-worlds','https://worldifact.test','DELETE'),{},network as any))!.status,405);assert.equal(calls,0)})
test('WebMCP can propose but never apply, buy, save or edit another world; unsupported browsers are honest',async()=>{const w=newGameWorld('Owned');let proposals=0;const tools=worldTools(()=>w,()=>{proposals++});assert.equal(JSON.parse(await tools[0].execute({worldId:w.id})).status,'READ_ONLY');await assert.rejects(tools[0].execute({worldId:OTHER}));await assert.rejects(tools[1].execute({worldId:w.id,command:'show stars',humanApproved:true}));assert.equal(JSON.parse(await tools[1].execute({worldId:w.id,command:'add jump button'})).status,'AWAITING_HUMAN_APPLY');assert.equal(w.controls.length,0);assert.equal(proposals,1);assert.equal(await registerWorldTools(undefined,()=>w,()=>{},new AbortController().signal),'WEBMCP_UNAVAILABLE')})
test('Creator can try two Astra jobs within 1500 points and preserves a nonrefundable provider reserve',async()=>{const a=fixture();await a.call('/grant',{id:'in_creator',credits:1500,subscriptionId:'sub_creator'});await a.call('/subscription',{id:'sub_creator',until:a.now()+31*86400000,active:true,revision:a.now(),plan:'creator',grantId:'in_creator'});const ids=[crypto.randomUUID(),crypto.randomUUID()];for(const id of ids){const r=await a.call('/reserve',{id,profile:'slow'});assert.equal(r.value.allowed,true);assert.equal(r.value.cost,250)}const status=(await a.call('/status')).value;assert.equal(status.credits,1000);assert.equal(status.creatorAstraRemaining,4);assert.equal(await a.storage.get('provider-budget-cents:v1'),700);await a.call('/settle',{id:ids[0],state:'failed'});assert.equal((await a.call('/status')).value.credits,1250);assert.equal(await a.storage.get('provider-budget-cents:v1'),700);assert.equal((await a.call('/status')).value.creatorAstraRemaining,4);assert.equal(providerReserveCents(1500),1050);assert.ok(planEconomics('creator').marginBps>=3000)})
test('Creator period cap is atomic, survives recreation, and topups cannot extend it',async()=>{const a=fixture();await a.call('/grant',{id:'in_creator',credits:1500});await a.call('/subscription',{id:'sub_creator',until:a.now()+31*86400000,active:true,revision:a.now(),plan:'creator',grantId:'in_creator'});await a.call('/grant',{id:'pi_topup',credits:1500});const ids=Array.from({length:14},()=>crypto.randomUUID());const results=await Promise.all(ids.map(id=>a.call('/reserve',{id,profile:'slow'})));assert.equal(results.filter(r=>r.value.allowed).length,6);assert.ok(results.filter(r=>!r.value.allowed).every(r=>r.value.reason==='CREATOR_ASTRA_PERIOD_LIMIT'));a.recreate();assert.equal((await a.call('/status')).value.creatorAstraRemaining,0);assert.equal((await a.call('/reserve',{id:ids[0],profile:'slow'})).value.repeated,true);assert.equal((await a.call('/status')).value.credits,1500);a.advance();assert.equal((await a.call('/reserve',{id:crypto.randomUUID(),profile:'slow'})).value.reason,'ASTRA_PLAN_REQUIRED')})
test('Creator quote shows 250 points but cannot bypass the global Astra readiness gate',()=>{const account={credits:1500,creatorAstraRemaining:6,generationCosts:{sol:50,astra:250,luna:15},subscription:{active:true,plan:'creator'},free:{fastRemaining:2},billingReview:false};const billing={plans:{creator:{checkoutReady:true},pro:{checkoutReady:true},studio:{checkoutReady:true}}};assert.equal(quoteGeneration('astra',account,billing,true).after,1250);assert.equal(quoteGeneration('astra',{...account,creatorAstraRemaining:0},billing,true).state,'blocked');assert.equal(quoteGeneration('astra',account,{plans:{...billing.plans,pro:{blockedReason:'ASTRA_COST_GUARD_REQUIRED'}}},true).state,'blocked')})
test('Shop does not mount the crossed-out world; Game Lab does not import the shared hub',async()=>{const portal=await readFile(new URL('../src/pages/PortalPage.tsx',import.meta.url),'utf8');assert.ok(portal.includes("if (app.route === '/shop') return <ShopPage />"));const editor=await readFile(new URL('../src/components/PersonalGameLab.tsx',import.meta.url),'utf8');const canvas=await readFile(new URL('../src/components/GameWorldCanvas.tsx',import.meta.url),'utf8');assert.doesNotMatch(editor+canvas,/import .*StartingWorld|queen\.glb|Mars landship/);assert.match(editor,/New game/);assert.match(editor,/GAME_TUTORIAL/);assert.match(editor,/storeGameBrief/);assert.match(editor,/library-access/);assert.doesNotMatch(editor+canvas,/\beval\(|new Function\(/)})
