import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { PORTALS } from '../src/config/portals.ts'
import { REFERENCE_LINKS } from '../src/config/references.ts'
import { renderShopMarkup } from './shop-render-helper.mjs'

test('native Shop presents a customer creation flow with cart and no visible engineering controls', async () => {
  const html = await renderShopMarkup()
  assert.match(html, /href="\/world"[^>]*>← Back to WORLDIFAKT/)
  for (const portal of PORTALS) assert.ok(html.includes(`href="${portal.route}"`))
  assert.match(html, /Describe it\.<br\/>See it in 3D\./)
  assert.match(html, /SLOW · QUALITY/)
  assert.match(html, /FAST · DRAFT/)
  assert.ok(html.indexOf('id="studio-mode"') < html.indexOf('id="studio-prompt"'))
  assert.doesNotMatch(html, /shop-funding-source|Check approved test pool|Turn your idea|WORLDIFACT STUDIO/)
  assert.match(html, /id="studio-prompt"/)
  assert.match(html, /id="studio-photos"/)
  assert.equal((html.match(/id="studio-mode"/g) ?? []).length, 1)
  assert.match(html, /GPT-6 ASTRA — 250 points per job/)
  assert.match(html, /GPT-6\.1 SOL — 50 points/)
  assert.match(html, /GPT-6 LUNA — 15 points/)
  assert.match(html, /Generate Astra\/Blender model · 250 points/)
  assert.match(html, /CUSTOMIZE &amp; ORDER/)
  assert.match(html, /Cart/)
  assert.match(html, /Specify model dimensions \(optional\)/)
  assert.doesNotMatch(html, /X width \(mm\)/)
  assert.doesNotMatch(html, /Y height \(mm\)/)
  assert.doesNotMatch(html, /Z depth \(mm\)/)
  const manufacturingSource = await readFile(new URL('../src/components/ShopManufacturingOptions.tsx', import.meta.url), 'utf8')
  assert.match(manufacturingSource, /dimensionsEnabled &&/)
  assert.match(manufacturingSource, /X width \(mm\)/)
  assert.match(manufacturingSource, /Y height \(mm\)/)
  assert.match(manufacturingSource, /Z depth \(mm\)/)
  assert.match(html, /shop-internal-only" hidden/)
  assert.doesNotMatch(html, /<iframe|<object|<embed|Opening the original generator/)
})

test('initial render checks cloud recovery before exposing any example preview or pre-purchase download', async () => {
  const html = await renderShopMarkup()
  assert.match(html, /Checking your account/)
  assert.doesNotMatch(html, /Example 3D product preview|assets\/model-[a-z]+\.webp/)
  assert.doesNotMatch(html, />Download GLB \+ embedded materials/)
  assert.doesNotMatch(html, /Model ID:/)
})

test('unavailable generation is customer-friendly and does not expose quota diagnostics', async () => {
  const html = await renderShopMarkup()
  assert.match(html, /type="submit" disabled=""/)
  assert.match(html, /Checking availability/)
  assert.match(html, /Preview DEMO · no API cost/)
  assert.match(html, /Checking your account before generation/)
  assert.match(html, /Free: up to 2 shared Sol\/Luna drafts per rolling 24 hours when funded capacity is available/)
  assert.match(html, /Experimental beta/)
  assert.doesNotMatch(html, /blocked by the exhausted pilot quota/)
})

test('original Studio remains isolated and hidden from the customer storefront', async () => {
  const html = await renderShopMarkup()
  const link = [...html.matchAll(/<a\b[^>]*>/g)].map(m => m[0]).find(a => a.includes(`href="${REFERENCE_LINKS.modelGenerator}"`))
  assert.ok(link)
  assert.match(link, /hidden=""/)
  assert.match(link, /target="_blank"/)
  assert.match(link, /rel="noopener noreferrer"/)
  const source = await readFile(new URL('../src/pages/ShopPage.tsx', import.meta.url), 'utf8')
  assert.doesNotMatch(source, /window\.location|document\.cookie|postMessage|<iframe/)
})

test('mobile layout keeps creation controls first and internal archive out of sight', async () => {
  const css = await readFile(new URL('../src/pages/ShopPage.css', import.meta.url), 'utf8')
  assert.match(css, /max-width:\s*760px/)
  assert.match(css, /\.native-shop-form\s*\{[^}]*order:\s*0/s)
  assert.match(css, /\.native-shop-preview\s*\{[^}]*order:\s*1/s)
  assert.match(css, /\.shop-internal-only\s*\{[^}]*display:\s*none/s)
  assert.doesNotMatch(css, /position:\s*(absolute|fixed)|webgl-fallback/)
  const html = await renderShopMarkup()
  assert.match(html, /<section class="shop-internal-only" hidden="" aria-labelledby="studio-archive-title">/)
  assert.match(html, /Digital 3D file:/)
  assert.match(html, /SLOW model downloads require an active subscription/)
})

test('historical Oracle jobs recover while explicit Astra blueprint and FAST generation keep modern transports', async () => {
  const source = await readFile(new URL('../src/pages/ShopPage.tsx', import.meta.url), 'utf8')
  const preview = await readFile(new URL('../src/components/DemoShopPreview.tsx', import.meta.url), 'utf8')
  assert.match(source, /Saved request did not finish/)
  assert.match(source, /Start a new model/)
  assert.match(source, /!terminal\(savedJob\?\.state\) && !savedJob\?\.reconciliationRequired && <p>Elapsed since this request was tracked:/)
  assert.doesNotMatch(source, /setNotice\(value\.detail\)/)
  assert.match(source, /await client\.dismissCurrent\(owner\)/)
  assert.match(source, /Checking your cloud job/)
  const client = await readFile(new URL('../src/lib/blueprintClient.ts', import.meta.url), 'utf8')
  assert.match(source, /directClient\.submit\(/)
  assert.match(client, /this\.fetcher\('\/api\/blueprint'/)
  assert.match(client, /validateGenerationResult/)
  assert.match(client, /X-WORLDIFACT-Request/)
  assert.match((await renderShopMarkup()).match(/<input[^>]*id="studio-photos"[^>]*>/)?.[0] ?? '', /multiple=""/)
  assert.match(source, /setFastResult\(result\)/)
  assert.doesNotMatch(source, /fastBudgetReady/)
  assert.doesNotMatch(source, /previous failed\/cancelled job was archived automatically/i)
  assert.match(preview, /LIVE · GENERATED SPEC \/ PROCEDURAL DRAFT/)
  assert.match(preview, /interior/)
})
