import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAccount } from '../lib/account'
import { KINDS, validateGenerationResult, type GenerationResult } from '../lib/blueprint'
import { newGameWorld, validateGameWorld, addWorldObject, mergeWorldBlueprint, proposeWorldCommand, applyWorldProposal, characterPrompt, GAME_TUTORIAL, WORLD_LIMITS, type GameWorld, type GameCharacter, type GameObject, type Point, type AssistantProposal } from '../lib/gameWorld'
import { gameAssets, putGameAsset, type LocalGameAsset } from '../lib/gameWorldAssets'
import { listStudioModels, readStudioModel, type StudioArchiveEntry } from '../lib/studioArchive'
import { storeGameBrief } from '../lib/gameHandoff'
import GameWorldCanvas, { emptyGameInput, triggerGameControl } from './GameWorldCanvas'
import GenerationCostNotice from './GenerationCostNotice'
import './PersonalGameLab.css'

type Tab='world'|'create'|'library'|'terrain'|'assistant'
const TABS:{id:Tab;title:string;icon:string}[]=[{id:'world',title:'World',icon:'◈'},{id:'create',title:'Create',icon:'✦'},{id:'library',title:'Library',icon:'▦'},{id:'terrain',title:'Terrain',icon:'△'},{id:'assistant',title:'Assistant',icon:'✧'}]
async function call(path:string,body?:unknown,signal?:AbortSignal){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:'no-store',redirect:'error',signal:signal??AbortSignal.timeout(15000)});if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('The service returned an unexpected page. Your draft is unchanged.');const text=await r.text();if(text.length>1_000_000)throw new Error('Unexpected service response.');const data=JSON.parse(text);if(!r.ok)throw new Error(typeof data.error==='string'?data.error:'The action could not be completed.');return data}
function portable(world:GameWorld){const url=URL.createObjectURL(new Blob([JSON.stringify(world,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`WORLDIFACT-world-${world.id}.json`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),10000)}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close()},[]);return <dialog className="game-modal" ref={dialog} onCancel={onClose} aria-label={title}><div className="game-modal-heading"><h2>{title}</h2><button type="button" onClick={onClose} aria-label="Close dialog">×</button></div>{children}</dialog>}
function Creator({onCreate,onClose}:{onCreate:(name:string,c:Partial<GameCharacter>)=>void;onClose:()=>void}){
 const [name,setName]=useState(''),[c,setC]=useState({name:'Explorer',description:'',outfit:'Exploration clothes',lettering:'',hair:'Brown',body:'Balanced',style:'Stylized',color:'#67dcc0'})
 return <Modal title="New game · describe your character" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onCreate(name,c)}}><label>Name your world<input required maxLength={80} autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="My first world"/></label><label>Character name<input required maxLength={60} value={c.name} onChange={e=>setC({...c,name:e.target.value})}/></label><label>How should your character look?<textarea maxLength={1000} rows={3} value={c.description} onChange={e=>setC({...c,description:e.target.value})} placeholder="Face, appearance, personality, distinctive details…"/></label><div className="game-two">{(['outfit','hair','body','style','lettering'] as const).map(key=><label key={key}>{({outfit:'Clothes',hair:'Hair color and shape',body:'Silhouette',style:'Visual style',lettering:'Text on clothing'})[key]}<input maxLength={key==='outfit'?200:key==='lettering'?80:100} value={c[key]} onChange={e=>setC({...c,[key]:e.target.value})}/></label>)}<label>Main clothing color<input type="color" value={c.color} onChange={e=>setC({...c,color:e.target.value})}/></label></div><p className="game-hint">Creating the world is free. The initial play-test mannequin is a local preview. A detailed AI character is a separate, explicitly priced generation.</p><button className="game-primary" disabled={!name.trim()||!c.name.trim()}>Create my world · 0 points</button></form></Modal>
}
function Editor({owner}:{owner:string}){
 const navigate=useNavigate(),[world,setWorld]=useState<GameWorld|null>(null),[worlds,setWorlds]=useState<GameWorld[]>([]),[tab,setTab]=useState<Tab>('world'),[create,setCreate]=useState(false),[tour,setTour]=useState<number|null>(null)
 const [point,setPoint]=useState<Point>({x:-9,z:0}),[selected,setSelected]=useState<string|null>(null),[placement,setPlacement]=useState<{kind:GameObject['kind'];id:string|null;name:string}|null>(null),[play,setPlay]=useState(false)
 const [models,setModels]=useState<LocalGameAsset[]>([]),[oldModels,setOldModels]=useState<StudioArchiveEntry[]>([]),[libraryBusy,setLibraryBusy]=useState(false)
 const [notice,setNotice]=useState('No AI cost to build, move, sculpt or play.'),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false)
 const [command,setCommand]=useState(''),[proposal,setProposal]=useState<AssistantProposal|null>(null),[aiPrompt,setAiPrompt]=useState(''),[model,setModel]=useState<'luna'|'sol'|'astra'>('luna'),[aiBusy,setAiBusy]=useState(false),[aiResult,setAiResult]=useState<{worldId:string;result:GenerationResult}|null>(null),[ready,setReady]=useState(false)
 const input=useRef(emptyGameInput()),history=useRef<GameWorld[]>([]),future=useRef<GameWorld[]>([]),worldRef=useRef(world),active=useRef(true),aiController=useRef<AbortController|null>(null),saveLock=useRef(false)
 worldRef.current=world
 const draftKey=`worldifact-personal-world:${owner}`
 useEffect(()=>{
  active.current=true;const controller=new AbortController()
  try{const raw=localStorage.getItem(draftKey);if(raw&&raw.length<=WORLD_LIMITS.bytes){setWorld(validateGameWorld(JSON.parse(raw)));setDirty(true);setNotice('Recovered your local draft. Save to your account after reviewing it.')}}catch{setError('A local draft could not be read. It was not deleted.')}
  call('/api/game-worlds',undefined,controller.signal).then(v=>{if(!active.current)return;setWorlds(v.worlds.map(validateGameWorld))}).catch(()=>{if(active.current)setNotice('Account storage is unavailable right now. Local editing and export still work.')})
  call('/api/health',undefined,controller.signal).then(v=>{if(active.current)setReady(v.generationReady===true)}).catch(()=>{})
  gameAssets(owner).then(v=>{if(active.current)setModels(v)}).catch(()=>{})
  return()=>{active.current=false;controller.abort();aiController.current?.abort();input.current=emptyGameInput()}
 },[owner,draftKey])
 useEffect(()=>{if(!world)return;const timer=window.setTimeout(()=>{try{localStorage.setItem(draftKey,JSON.stringify(world))}catch{setError('Device storage is full or disabled. Export a world backup now.')}},400);return()=>window.clearTimeout(timer)},[world,draftKey])
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty||aiBusy){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty,aiBusy])
 function change(next:GameWorld){try{const valid=validateGameWorld(next);if(worldRef.current){history.current.push(worldRef.current);history.current=history.current.slice(-WORLD_LIMITS.history)}future.current=[];worldRef.current=valid;setWorld(valid);setDirty(true);setError('')}catch(e){setError(e instanceof Error?e.message:'Invalid edit.')}}
 function undo(redo=false){const from=redo?future.current:history.current,to=redo?history.current:future.current;const next=from.pop();if(next&&worldRef.current){to.push(worldRef.current);const value={...next,revision:worldRef.current.revision,updatedAt:worldRef.current.updatedAt};worldRef.current=value;setWorld(value);setDirty(true)}}
 function choosePoint(p:Point,id:string|null){setPoint(p);setSelected(id);if(placement&&worldRef.current){try{change(addWorldObject(worldRef.current,placement.kind,p,placement.id,placement.name));setPlacement(null);setNotice('Model placed. Use its transform controls or Undo.')}catch(e){setError(e instanceof Error?e.message:'The model could not be placed.')}}}
 function act(p:AssistantProposal){if(!worldRef.current)return;try{change(applyWorldProposal(worldRef.current,p,point));setNotice(`${p.label} · 0 AI cost`);setProposal(null)}catch(e){setError(e instanceof Error?e.message:'Cannot apply this edit.')}}
 async function save(){const value=worldRef.current;if(!value||saveLock.current)return;saveLock.current=true;setSaving(true);setError('');try{const data=await call('/api/game-worlds',{world:value,expectedRevision:value.revision});if(!active.current)return;const saved=validateGameWorld(data.world);setWorlds(items=>[saved,...items.filter(v=>v.id!==saved.id)]);if(worldRef.current?.id===value.id){const unchanged=worldRef.current===value;const next=unchanged?saved:{...worldRef.current,revision:saved.revision,updatedAt:saved.updatedAt};worldRef.current=next;setWorld(next);setDirty(!unchanged)}setNotice('Saved to your account. Original GLB files remain on this device.')}catch(e){if(active.current)setError(e instanceof Error?e.message:'Save failed. Export your local backup.')}finally{saveLock.current=false;if(active.current)setSaving(false)}}
 async function refreshLibrary(){if(libraryBusy)return;setLibraryBusy(true);setError('');try{const local=await gameAssets(owner);if(active.current)setModels(local);const candidates=(await listStudioModels()).slice(0,32);if(candidates.length){const owned=await call('/api/game-worlds/library-access',{ids:candidates.map(v=>v.id)});if(active.current)setOldModels(candidates.filter(v=>owned.ids.includes(v.id)))}setNotice('Library refreshed. Only completed models owned by this signed-in account are shown.')}catch{if(active.current)setError('The old gallery could not be verified. Import a GLB you own instead; no other account library is exposed.')}finally{if(active.current)setLibraryBusy(false)}}
 async function importBlob(blob:Blob,name:string){setLibraryBusy(true);setError('');try{const entry=await putGameAsset(owner,name,blob);if(!active.current)return;setModels(await gameAssets(owner));setPlacement({kind:'local-model',id:entry.id,name:entry.name});setNotice('Tap a point in the world to place this model.')}catch(e){if(active.current)setError(e instanceof Error?e.message:'Model import failed.')}finally{if(active.current)setLibraryBusy(false)}}
 async function importOld(entry:StudioArchiveEntry){if(libraryBusy)return;setLibraryBusy(true);try{const proof=await call('/api/game-worlds/library-access',{ids:[entry.id]});if(!proof.ids.includes(entry.id))throw new Error('Model ownership could not be confirmed.');await importBlob(await readStudioModel(entry.id),entry.prompt)}catch(e){setError(e instanceof Error?e.message:'Model unavailable.');setLibraryBusy(false)}}
 function shopCharacter(){if(!world)return;try{storeGameBrief(owner,characterPrompt(world.character));navigate('/shop?from=game-lab')}catch{setError('Character handoff could not be saved. Copy the description into AI Shop manually.')}}
 async function generate(){if(!world||aiBusy||!ready||model==='astra')return;const id=world.id,chosen=model;const requestId=crypto.randomUUID();try{sessionStorage.setItem(`worldifact-world-ai:${owner}`,JSON.stringify({id,requestId,model:chosen,prompt:aiPrompt,status:'submitted'}))}catch{setError('Recovery storage is unavailable; no paid request started.');return}setAiBusy(true);setError('');const controller=new AbortController();aiController.current=controller;const timer=window.setTimeout(()=>controller.abort(),45000)
  try{const response=await fetch('/api/blueprint',{method:'POST',headers:{'Content-Type':'application/json','X-WORLDIFACT-Request':requestId},body:JSON.stringify({worldId:'ai-game-lab',mode:'live',model:chosen,prompt:aiPrompt}),signal:controller.signal,redirect:'error'});const raw=await response.text();if(raw.length>200000)throw new Error('Unexpected AI response size.');const data=JSON.parse(raw);if(!response.ok)throw new Error(data.error||'Generation did not complete.');const result=validateGenerationResult(data);if(result.mode!=='LIVE'||result.model!==`gpt-6-${chosen}`)throw new Error('The selected live model was not returned. No substitution was accepted.');try{sessionStorage.setItem(`worldifact-world-ai:${owner}`,JSON.stringify({id,requestId,model:chosen,result,status:'completed'}))}catch{ /* Keep the result on screen for explicit application/export. */ }if(active.current&&worldRef.current?.id===id){setAiResult({worldId:id,result});setNotice('AI specification received. Review and apply its objects; your current world has not been replaced.')}
  }catch(e){if(active.current)setError(e instanceof Error&&e.name==='AbortError'?'Stopped waiting. The provider outcome may be uncertain; no automatic retry or refund is inferred.':e instanceof Error?e.message:'Generation unavailable.')}finally{window.clearTimeout(timer);aiController.current=null;if(active.current)setAiBusy(false)}
 }
 const object=world?.objects.find(o=>o.id===selected)
 const updateObject=(values:Partial<GameObject>)=>{if(world&&object)change({...world,objects:world.objects.map(o=>o.id===object.id?{...o,...values}:o)})}
 const restore=(v:GameWorld)=>{if((dirty||aiBusy)&&!window.confirm('Leave this draft? Its local backup is not a cloud save. Export or save it first.'))return;setWorld(v);worldRef.current=v;history.current=[];future.current=[];setDirty(false);setSelected(null);setPlacement(null);setPlay(false);input.current=emptyGameInput()}
 return <section className="personal-game-lab">
  {!world?<div className="game-launch"><GameWorldCanvas world={null} owner={owner} play={false} point={point} selected={null} input={input} onPoint={choosePoint} onError={setError}/><div className="game-launch-copy"><span className="game-eyebrow">YOUR IDEAS. YOUR UNIVERSE.</span><h1>Create your own world.</h1><p>Start with a meadow and a river. Build a game that is yours.</p><button className="game-primary" onClick={()=>setCreate(true)}>✦ New game · 0 points</button><small>World editing is local. AI runs only when you explicitly request it.</small>{worlds.length>0&&<div className="game-project-list"><h2>Your saved worlds</h2>{worlds.map(v=><button key={v.id} onClick={()=>restore(v)}>{v.name} ↗</button>)}</div>}</div></div>:<>
   <header className="game-editor-heading"><div><span className="game-eyebrow">MY GAME STUDIO · PRIVATE WORLD</span><h1>{world.name}</h1><small>{dirty?'Local draft · unsaved account changes':`Account revision ${world.revision}`} · Models stored on this device</small></div><div className="game-actions"><button disabled={aiBusy||saving} onClick={()=>setCreate(true)}>＋ New game</button><button onClick={()=>{setTour(0);setTab('world')}}>5-step tutorial</button><button onClick={()=>{setPlay(v=>!v);input.current=emptyGameInput()}}>{play?'■ Edit world':'▶ Play test'}</button><button className="game-primary" disabled={saving||!dirty} onClick={()=>void save()}>{saving?'Saving…':'Save to account'}</button></div></header>
   <div className="game-editor-grid"><div className="game-stage"><GameWorldCanvas key={world.id} world={world} owner={owner} play={play} point={point} selected={selected} input={input} onPoint={choosePoint} onError={setError}/>
    <div className="game-stage-caption">{play?'PLAY TEST · WASD / arrows · drag to look':'EDIT · drag to orbit · tap ground to select a point'}<br/>{placement?`PLACE: ${placement.name} — tap the ground`:`Selected point ${point.x.toFixed(1)}, ${point.z.toFixed(1)}`}</div>
    {!play&&<div className="game-stage-tools"><button disabled={!history.current.length} onClick={()=>undo()}>↶ Undo</button><button disabled={!future.current.length} onClick={()=>undo(true)}>↷ Redo</button>{placement&&<button onClick={()=>setPlacement(null)}>Cancel placement</button>}</div>}
    {play&&<><div className="game-dpad" aria-label="Movement controls">{(['forward','left','back','right'] as const).map((dir,i)=><button key={dir} aria-label={`Move ${dir}`} className={`game-dir-${dir}`} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);input.current[dir]=true}} onPointerUp={()=>{input.current[dir]=false}} onPointerCancel={()=>{input.current[dir]=false}} onLostPointerCapture={()=>{input.current[dir]=false}} onKeyDown={e=>{if(e.key===' '||e.key==='Enter')input.current[dir]=true}} onKeyUp={()=>{input.current[dir]=false}}>{['↑','←','↓','→'][i]}</button>)}</div><div className="game-play-buttons">{world.controls.map(c=><button key={c.action} onClick={()=>{if(c.action==='sprint')input.current.sprint=!input.current.sprint;else triggerGameControl(input.current,c.action,true)}}>{c.label}</button>)}</div></>}
   </div><aside className="game-sidebar"><nav className="game-tabbar" aria-label="Game creation tools">{TABS.map(t=><button key={t.id} className={tab===t.id?'active':''} aria-pressed={tab===t.id} onClick={()=>{setTab(t.id);if(t.id==='library'&&!models.length&&!oldModels.length)void refreshLibrary()}}><span>{t.icon}</span>{t.title}</button>)}</nav>
    <div className="game-panel" id={`game-panel-${tab}`}>
    {tab==='world'&&<><h2>Your world</h2><label>World name<input value={world.name} maxLength={80} onChange={e=>{if(e.target.value.trim())change({...world,name:e.target.value})}}/></label><label>Open a saved world<select value="" disabled={aiBusy||saving} onChange={e=>{const v=worlds.find(w=>w.id===e.target.value);if(v)restore(v)}}><option value="">Choose one of your worlds…</option>{worlds.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><div className="game-panel-section"><h3>{world.character.name}</h3><p>{world.character.description||'Your character brief is ready for editing.'}</p><p className="game-hint">Play-test appearance is a local mannequin until you choose a library model as the player. Uploaded meshes move as a unit; automatic rigging is not claimed.</p><button onClick={shopCharacter}>Create this character in AI Shop ↗</button></div><label>Select an object<select value={selected??''} onChange={e=>setSelected(e.target.value||null)}><option value="">No object selected</option>{world.objects.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
      {object&&<div className="game-panel-section"><h3>Transform · {object.name}</h3>{(['x','z','y','scale','rotation'] as const).map(k=><label key={k}>{k} · {object[k].toFixed(1)}<input type="range" min={k==='scale'?.1:k==='rotation'?0:k==='y'?-5:-40} max={k==='scale'?8:k==='rotation'?360:k==='y'?30:40} step={k==='rotation'?1:.1} value={object[k]} onChange={e=>updateObject({[k]:Number(e.target.value)})}/></label>)}<button onClick={()=>updateObject(point)}>Move to selected point</button>{object.kind==='local-model'&&<button onClick={()=>change({...world,playerModelId:object.id})}>Use as my player</button>}<button onClick={()=>{change({...world,objects:world.objects.filter(o=>o.id!==object.id),playerModelId:world.playerModelId===object.id?null:world.playerModelId});setSelected(null)}}>Remove this placement · undo available</button></div>}
      <div className="game-panel-section"><h3>Backups</h3><button onClick={()=>portable(world)}>Export world project · JSON</button><label>Import world project<input type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>WORLD_LIMITS.bytes){setError('Project file is too large.');return}void file.text().then(text=>{const v=validateGameWorld(JSON.parse(text));if(!active.current)return;change({...v,id:crypto.randomUUID(),revision:0,updatedAt:new Date().toISOString()});setNotice('Imported as a new private world. Original local GLBs may need to be imported separately.')}).catch(()=>setError('The file is not a supported world project.'))}}/></label><small>JSON contains your layout and controls, not model binaries or a standalone game executable.</small></div></>}
    {tab==='terrain'&&<><h2>Shape your landscape</h2><p>Tap a point on the ground, then choose a tool. Sculpting uses no AI.</p><div className="game-toolgrid"><button onClick={()=>act({command:'hill',label:'Raise a mountain'})}>△ Raise mountain</button><button onClick={()=>act({command:'valley',label:'Dig a valley'})}>▽ Dig valley</button><button onClick={()=>act({command:'stars',label:'Show stars'})}>✦ Show stars</button><button onClick={()=>act({command:'day',label:'Daylight'})}>☀ Daylight</button></div><label>Grass quality<select value={world.grass} onChange={e=>change({...world,grass:e.target.value as 'balanced'|'lush'})}><option value="balanced">Balanced · mobile friendly</option><option value="lush">Lush · higher local GPU use</option></select></label><small>{world.terrain.length}/{WORLD_LIMITS.terrain} terrain edits. Water is a visual surface, not a fluid simulation.</small><h3>Free built-in objects</h3><div className="game-toolgrid">{KINDS.map(kind=><button key={kind} onClick={()=>{setPlacement({kind,id:null,name:kind});setNotice('Tap ground to place your selected object.')}}>{kind}</button>)}</div></>}
    {tab==='library'&&<><h2>My model library</h2><p>Add a model, then tap the ground to place it.</p><button disabled={libraryBusy} onClick={()=>void refreshLibrary()}>{libraryBusy?'Reading library…':'↻ Refresh owned models'}</button><label>Import a GLB you own<input type="file" accept=".glb,model/gltf-binary" disabled={libraryBusy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void importBlob(file,file.name)}}/></label><small>64 MB/model; 192 MB/device library. No server upload or AI charge. The scene has a mobile geometry safety limit.</small>{models.map(m=><article className="game-library-item" key={m.id}><b>{m.name}</b><small>{(m.bytes/1048576).toFixed(1)} MB · {m.triangles.toLocaleString()} triangles</small><button onClick={()=>setPlacement({kind:'local-model',id:m.id,name:m.name})}>Add to my world →</button></article>)}{oldModels.length>0&&<h3>Completed AI Shop models on this device</h3>}{oldModels.map(m=><article className="game-library-item" key={m.id}><b>{m.prompt.slice(0,100)}</b><small>{(m.byteLength/1048576).toFixed(1)} MB · {m.review}</small><button disabled={libraryBusy} onClick={()=>void importOld(m)}>Import and place →</button></article>)}{!models.length&&!oldModels.length&&!libraryBusy&&<p>No owned models found on this device. Create one in AI Shop or import your original GLB.</p>}<Link to="/account/models">Open my model gallery ↗</Link></>}
    {tab==='create'&&<><h2>Create with AI</h2><p>AI suggests objects. Applying them is separate and never deletes your current world.</p><label>AI model<select value={model} disabled={aiBusy} onChange={e=>setModel(e.target.value as typeof model)}><option value="luna">GPT-6 Luna · 15 points</option><option value="sol">GPT-6 Sol · 50 points</option><option value="astra">GPT-6 Astra · 250 points · AI Shop</option></select></label><GenerationCostNotice model={model} busy={aiBusy}/><label>Describe models for your world<textarea maxLength={2000} rows={5} value={aiPrompt} disabled={aiBusy} onChange={e=>setAiPrompt(e.target.value)} placeholder="A solar exploration base with trees and a small workshop…"/></label>{model==='astra'?<button onClick={()=>navigate('/shop?model=astra')}>Open detailed Astra creation in AI Shop ↗</button>:<button className="game-primary" disabled={aiBusy||!ready||aiPrompt.trim().length<3} onClick={()=>void generate()}>{aiBusy?'Generating once…':`Send once to ${model.toUpperCase()} · ${model==='luna'?15:50} points / paid attempt`}</button>}{!ready&&<small>Live AI is not confirmed ready. Local tools and your library still work without AI.</small>}{aiBusy&&<button onClick={()=>aiController.current?.abort()}>Stop waiting · does not cancel billing</button>}{aiResult&&aiResult.worldId===world.id&&<div className="game-panel-section"><h3>{aiResult.result.blueprint.title}</h3><p>{aiResult.result.blueprint.objects.map(o=>o.name).join(' · ')}</p><small>LIVE specification · procedural geometry · {aiResult.result.model}</small><button onClick={()=>{try{change(mergeWorldBlueprint(world,aiResult.result.blueprint));setAiResult(null)}catch(e){setError(e instanceof Error?e.message:'Scene limit reached.')}}}>Apply {aiResult.result.blueprint.objects.length} objects to my world · 0 extra points</button></div>}<Link to="/shop">Detailed models, image references and character creation → AI Shop</Link></>}
    {tab==='assistant'&&<><span className="game-eyebrow">LOCAL ASSISTANT · 0 API COST</span><h2>Tell your world what to do.</h2><p>Add working controls or shape the scene with a short command. Review every proposed change.</p><form onSubmit={e=>{e.preventDefault();const p=proposeWorldCommand(command);setProposal(p);if(!p)setNotice('Try: add jump button, add fly button, show stars, place a tree, or wykop dolinę. Use Create for an AI-generated scene.')}}><label>Editor command<textarea rows={4} maxLength={1000} value={command} onChange={e=>setCommand(e.target.value)} placeholder="Dodaj przycisk skoku / Add jump button"/></label><button>Preview action · 0 points</button></form>{proposal&&<div className="game-panel-section"><b>{proposal.label}</b><p>Target: {world.name} · point {point.x.toFixed(1)}, {point.z.toFixed(1)}</p><button className="game-primary" onClick={()=>act(proposal)}>Apply to my world</button></div>}<div className="game-toolgrid">{['Add jump button','Add fly button','Add sprint button','Show stars','Dig a valley','Place a tree'].map(s=><button key={s} onClick={()=>{setCommand(s);setProposal(proposeWorldCommand(s))}}>{s}</button>)}</div><h3>My game buttons</h3>{world.controls.map(c=><div className="game-control-row" key={c.action}><label>{c.action}<input maxLength={30} value={c.label} onChange={e=>{if(e.target.value.trim())change({...world,controls:world.controls.map(b=>b.action===c.action?{...b,label:e.target.value}:b)})}}/></label><button aria-label={`Remove ${c.action} control`} onClick={()=>change({...world,controls:world.controls.filter(b=>b.action!==c.action)})}>×</button></div>)}<details><summary>Codex / MCP integration status</summary><p>This assistant executes validated local editor actions, not a hosted Codex agent. External agents and arbitrary generated JavaScript are not enabled. No paid agent loop or remote tool execution is started here.</p><p>The repository includes an editor action contract for reviewed future adapters. AI scene requests use the existing priced model route.</p></details></>}
    </div></aside></div>
  </>}
  <div className="game-feedback" role="status">{notice}</div>{error&&<p className="game-error" role="alert">{error}</p>}
  {create&&<Creator onClose={()=>setCreate(false)} onCreate={(name,c)=>{if(dirty&&!window.confirm('Start a new world? Save or export the previous draft first.'))return;try{const value=newGameWorld(name,c);history.current=[];future.current=[];worldRef.current=value;setWorld(value);setDirty(true);setCreate(false);setTour(0);setTab('world');setPlay(false);setSelected(null);setPlacement(null);setPoint({x:-9,z:0})}catch(e){setError(e instanceof Error?e.message:'Invalid world name.')}}/>}
  {tour!==null&&<Modal title={GAME_TUTORIAL[tour].title} onClose={()=>setTour(null)}><div className="game-tour-progress">{GAME_TUTORIAL.map((s,i)=><button key={s.title} aria-label={`Tutorial step ${i+1}`} aria-current={tour===i?'step':undefined} onClick={()=>{setTour(i);setTab(s.tab)}}>{i+1}</button>)}</div><p>{GAME_TUTORIAL[tour].text}</p><div className="game-actions"><button disabled={tour===0} onClick={()=>{setTour(tour-1);setTab(GAME_TUTORIAL[tour-1].tab)}}>← Back</button><button className="game-primary" onClick={()=>{if(tour===4)setTour(null);else{setTour(tour+1);setTab(GAME_TUTORIAL[tour+1].tab)}}}>{tour===4?'Start building':'Next →'}</button></div></Modal>}
 </section>
}
export default function PersonalGameLab(){const {user,loading}=useAccount();const input=useRef(emptyGameInput());if(loading)return <p role="status">Opening your game studio…</p>;if(!user)return <section className="personal-game-lab game-launch"><GameWorldCanvas world={null} owner="guest" play={false} point={{x:0,z:0}} selected={null} input={input} onPoint={()=>{}} onError={()=>{}}/><div className="game-launch-copy"><h1>Create your own world.</h1><p>A meadow, a river, and a new game made by you.</p><Link className="game-primary" to="/login?returnTo=%2Flab">Sign in to create your private world</Link><small>Local world tools do not use paid AI. Account isolation protects every saved world.</small></div></section>;return <Editor key={user.id} owner={user.id}/>}
